a = input('digite algo: ')
print('o tipo primitivo é ', type(a))
print('só tem espaços ? ', a.isspace())
print('é um numero? ', a.isnumeric())
print('é alfabetico? ', a.isalpha())
print('é alfanumerico? ', a.isalnum())
print('é maius? ', a.isupper())
print('é min? ', a.islower())
print('esta capitalizado? ', a.istitle())
